"""initial migration

Revision ID: 45b7f0574a34
Revises: 
Create Date: 2026-05-01 16:04:45.921194

"""
from typing import Sequence, Union

from alembic import op #type:ignore
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45b7f0574a34'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinics',
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('doctor_name', sa.Text(), nullable=False),
    sa.Column('clinic_name', sa.Text(), nullable=False),
    sa.Column('clinic_salt', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('clinic_id'),
    sa.UniqueConstraint('clinic_salt')
    )
    op.create_table('events',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('network_token', sa.Text(), nullable=False),
    sa.Column('local_token', sa.Text(), nullable=False),
    sa.Column('daily_token_number', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.clinic_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_events_local_token'), 'events', ['local_token'], unique=False)
    op.create_index(op.f('ix_events_network_token'), 'events', ['network_token'], unique=False)
    op.create_index(op.f('ix_events_status'), 'events', ['status'], unique=False)
    op.create_table('prescriptions',
    sa.Column('prescription_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('network_token', sa.Text(), nullable=False),
    sa.Column('local_token', sa.Text(), nullable=False),
    sa.Column('medicine_name', sa.Text(), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('drug_category', sa.Text(), nullable=True),
    sa.Column('inferred_symptom', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], ),
    sa.PrimaryKeyConstraint('prescription_id')
    )
    op.create_index(op.f('ix_prescriptions_local_token'), 'prescriptions', ['local_token'], unique=False)
    op.create_index(op.f('ix_prescriptions_network_token'), 'prescriptions', ['network_token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prescriptions_network_token'), table_name='prescriptions')
    op.drop_index(op.f('ix_prescriptions_local_token'), table_name='prescriptions')
    op.drop_table('prescriptions')
    op.drop_index(op.f('ix_events_status'), table_name='events')
    op.drop_index(op.f('ix_events_network_token'), table_name='events')
    op.drop_index(op.f('ix_events_local_token'), table_name='events')
    op.drop_table('events')
    op.drop_table('clinics')
    # ### end Alembic commands ###
